# Mnogu mi bese komplicirano sega da napravam CMake

CC=g++
DD=dist

all:
	mkdir -p $(DD)
	$(CC) tests/1.cpp impl.cpp -o $(DD)/1
	$(CC) tests/2.cpp impl.cpp -o $(DD)/2
	$(CC) tests/3.cpp impl.cpp -o $(DD)/3
	$(CC) tests/4.cpp impl.cpp -o $(DD)/4
	$(CC) tests/5.cpp impl.cpp -o $(DD)/5